# =============================================================================
# AI-SPM Service Mesh - Kubernetes Services
# =============================================================================
# These services define the network endpoints for service discovery and
# load balancing within the Istio service mesh.
# =============================================================================

# API Gateway Service
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: ai-spm
  labels:
    app: api-gateway
    service: api-gateway
    tier: frontend
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: api-gateway
  type: ClusterIP
---
# AI Scanner Service
apiVersion: v1
kind: Service
metadata:
  name: ai-scanner
  namespace: ai-spm
  labels:
    app: ai-scanner
    service: ai-scanner
    tier: microservice
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: ai-scanner
  type: ClusterIP
---
# Data Integrity Service
apiVersion: v1
kind: Service
metadata:
  name: data-integrity
  namespace: ai-spm
  labels:
    app: data-integrity
    service: data-integrity
    tier: microservice
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
    name: http
  selector:
    app: data-integrity
  type: ClusterIP
---
# Wiz Integration Service
apiVersion: v1
kind: Service
metadata:
  name: wiz-integration
  namespace: ai-spm
  labels:
    app: wiz-integration
    service: wiz-integration
    tier: microservice
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - port: 8003
    targetPort: 8003
    protocol: TCP
    name: http
  selector:
    app: wiz-integration
  type: ClusterIP
---
# Compliance Engine Service
apiVersion: v1
kind: Service
metadata:
  name: compliance-engine
  namespace: ai-spm
  labels:
    app: compliance-engine
    service: compliance-engine
    tier: microservice
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - port: 8004
    targetPort: 8004
    protocol: TCP
    name: http
  selector:
    app: compliance-engine
  type: ClusterIP
---
# Database Service
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: ai-spm
  labels:
    app: database
    service: database
    tier: data
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: database
  type: ClusterIP
---
# Headless Service for Database StatefulSet (if needed for clustering)
apiVersion: v1
kind: Service
metadata:
  name: database-headless
  namespace: ai-spm
  labels:
    app: database
    service: database-headless
    tier: data
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: database
  clusterIP: None  # Headless service for StatefulSet